# ————————————————————————————————————————————————
# Copyright (c) Edrow, All rights reserved.
#              _       __            _
#   /\ /\_   _| |__   / /  ___   ___| | __
#  / //_/ | | | '_ \ / /  / _ \ / __| |/ /
# / __ \| |_| | |_) / /__| (_) | (__|   <
# \/  \/ \__,_|_.__/\____/\___/ \___|_|\_\
#
# Website: https://dev.dawbee.fr/kublock
# ————————————————————————————————————————————————

[general]
# Choose your language, you can choose between en_US, fr_FR or create your translation file.
language = "en_US"

allow_redstone = true
autolock = false


[features]
particles = true
highlight = true
holograms = true
commands = true
tutorial = false
effects = true
sounds = true

[gui]
enabled = true

[protected]
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
blocks = [ "CHEST", "TRAPPED_CHEST" ]
worlds = [ "world", "world_nether", "world_the_end" ]

[permissions]

[integration]
worldguard = false
coreprotect = false
griefprevention = false

[core]
update_notify = true