# ————————————————————————————————————————————————
# Copyright (c) Edrow, All rights reserved.
#              _       __            _
#   /\ /\_   _| |__   / /  ___   ___| | __
#  / //_/ | | | '_ \ / /  / _ \ / __| |/ /
# / __ \| |_| | |_) / /__| (_) | (__|   <
# \/  \/ \__,_|_.__/\____/\___/ \___|_|\_\
#
# Website: https://dev.dawbee.fr/kublock
# ————————————————————————————————————————————————

# Choose your language, you can choose between en_US, fr_FR or create your translation file.
language: en_US
metrics: true

allow_redstone: true
autolock: false


particles: true
highlight: true
holograms: true
commands: true
tutorial: false
effects: true
  sounds:true

# SNEAK_LEFT_CLICK, SNEAK_RIGHT_CLICK, LEFT_CLICK, RIGHT_CLICK
on_event: SNEAK_LEFT_CLICK

# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
blocks:
  - CHEST
  - TRAPPED_CHEST
  - ENDER_CHEST
  - BARREL
  - FURNACE
  - SMOKER
  - BLAST_FURNACE
  - LODESTONE
  - RESPAWN_ANCHOR
  - BEEHIVE
  - HOPPER
  - DISPENSER
  - DROPPER
  - LECTERN
  - COMPOSTER
  - CARTOGRAPHY_TABLE
  - FLETCHING_TABLE
  - GRINDSTONE
  - SMITHING_TABLE
  - LOOM
  - STONECUTTER
  - IRON_DOOR
  - OAK_DOOR
  - SPRUCE_DOOR
  - BIRCH_DOOR
  - JUNGLE_DOOR
  - ACACIA_DOOR
  - DARK_OAK_DOOR
  - CRIMSON_DOOR
  - WARPED_DOOR
  - IRON_TRAPDOOR
  - OAK_TRAPDOOR
  - SPRUCE_TRAPDOOR
  - BIRCH_TRAPDOOR
  - JUNGLE_TRAPDOOR
  - ACACIA_TRAPDOOR
  - DARK_OAK_TRAPDOOR
  - CRIMSON_TRAPDOOR
  - WARPED_TRAPDOOR
  - OAK_FENCE_GATE
  - SPRUCE_FENCE_GATE
  - BIRCH_FENCE_GATE
  - JUNGLE_FENCE_GATE
  - ACACIA_FENCE_GATE
  - DARK_OAK_FENCE_GATE
  - CRIMSON_FENCE_GATE
  - WARPED_FENCE_GATE
  - ANVIL
  - CHIPPED_ANVIL
  - DAMAGED_ANVIL
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX

worlds:
  - world
  - world_nether
  - world_the_end

worldguard: false
coreprotect: false
griefprevention: false

update_notify: true